export interface ChannelField { key: string; label: string; required?: boolean }

export const CHANNEL_PRESETS: Record<string, ChannelField[]> = {
  google_shopping: [
    { key: "g:id",                    label: "ID",                     required: true },
    { key: "g:title",                 label: "Title",                  required: true },
    { key: "g:description",           label: "Description",            required: true },
    { key: "g:link",                  label: "Product URL",            required: true },
    { key: "g:image_link",            label: "Image URL",              required: true },
    { key: "g:availability",          label: "Availability",           required: true },
    { key: "g:price",                 label: "Price",                  required: true },
    { key: "g:brand",                 label: "Brand" },
    { key: "g:condition",             label: "Condition" },
    { key: "g:gtin",                  label: "GTIN / SKU" },
    { key: "g:product_type",          label: "Product Type" },
    { key: "g:google_product_category", label: "Google Category" },
    { key: "g:mpn",                   label: "MPN" },
    { key: "g:sale_price",            label: "Sale Price" },
    { key: "g:item_group_id",         label: "Item Group ID" },
  ],
  meta: [
    { key: "id",           label: "ID",           required: true },
    { key: "title",        label: "Title",         required: true },
    { key: "description",  label: "Description" },
    { key: "availability", label: "Availability",  required: true },
    { key: "condition",    label: "Condition" },
    { key: "price",        label: "Price",         required: true },
    { key: "link",         label: "Product URL",   required: true },
    { key: "image_link",   label: "Image URL" },
    { key: "brand",        label: "Brand" },
    { key: "retailer_id",  label: "Retailer ID" },
    { key: "sale_price",   label: "Sale Price" },
  ],
  tiktok: [
    { key: "sku_id",      label: "SKU ID",      required: true },
    { key: "item_name",   label: "Title",        required: true },
    { key: "description", label: "Description" },
    { key: "price",       label: "Price",        required: true },
    { key: "link",        label: "Product URL" },
    { key: "image_url",   label: "Image URL" },
    { key: "availability", label: "Availability" },
    { key: "condition",   label: "Condition" },
    { key: "brand",       label: "Brand" },
  ],
  custom: [],
};

export const PRODUCT_ATTRIBUTES = [
  { key: "id",              label: "Product ID" },
  { key: "variantId",       label: "Variant ID" },
  { key: "sku",             label: "SKU" },
  { key: "name",            label: "Product Name" },
  { key: "variantName",     label: "Variant Name" },
  { key: "description",     label: "Description (HTML stripped)" },
  { key: "shortDescription", label: "Short Description" },
  { key: "price",           label: "Price (converted)" },
  { key: "compareAtPrice",  label: "Compare At Price (converted)" },
  { key: "stock",           label: "Stock Count" },
  { key: "availability",    label: "Availability (in stock / out of stock)" },
  { key: "category",        label: "Category Name" },
  { key: "platform",        label: "Platform" },
  { key: "imageUrl",        label: "Image URL" },
  { key: "slug",            label: "Product URL" },
  { key: "condition",       label: "Condition (always: new)" },
];

export const FILTER_FIELDS = [
  { key: "price",           label: "Price (USD)" },
  { key: "stock",           label: "Stock Count" },
  { key: "category",        label: "Category" },
  { key: "platform",        label: "Platform" },
  { key: "name",            label: "Product Name" },
  { key: "sku",             label: "SKU" },
  { key: "isActive",        label: "Is Active" },
  { key: "availability",    label: "Availability" },
];
