import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import adminRouter from "./admin";
import adminDashboardRouter from "./admin-dashboard";
import adminAnalyticsRouter from "./admin-analytics";
import adminProductsRouter from "./admin-products";
import adminCategoriesRouter from "./admin-categories";
import adminOrdersRouter from "./admin-orders";
import adminKeysRouter from "./admin-keys";
import adminClaimsRouter from "./admin-claims";
import adminDiscountsRouter from "./admin-discounts";
import adminCustomersRouter from "./admin-customers";
import adminReviewsRouter from "./admin-reviews";
import adminBannersRouter from "./admin-banners";
import adminPagesRouter from "./admin-pages";
import adminSettingsRouter from "./admin-settings";
import adminSettingsExtraRouter from "./admin-settings-extra";
import adminWebhooksChatRouter from "./admin-webhooks-chat";
import adminAuditRouter from "./admin-audit";
import adminBalanceRouter from "./admin-balance";
import adminUpsellRouter from "./admin-upsell";
import adminHomepageRouter from "./admin-homepage";
import adminBrandsRouter from "./admin-brands";
import adminEmailTemplatesRouter from "./admin-email-templates";
import adminTaxRouter from "./admin-tax";
import adminUsersRouter from "./admin-users";
import adminRefundsRouter from "./admin-refunds";
import adminNotificationsRouter from "./admin-notifications";
import adminSeoTrackingRouter from "./admin-seo-tracking";
import adminGiftCardsRouter from "./admin-gift-cards";
import giftCardsRouter from "./gift-cards";
import couponsRouter from "./coupons";
import ordersRouter from "./orders";
import checkoutOffersRouter from "./checkout-offers";
import orderLookupRouter from "./order-lookup";
import wishlistRouter from "./wishlist";
import currenciesRouter from "./currencies";
import webhooksRouter from "./webhooks";
import searchRouter from "./search";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(adminRouter);
router.use(adminDashboardRouter);
router.use(adminAnalyticsRouter);
router.use(adminProductsRouter);
router.use(adminCategoriesRouter);
router.use(adminOrdersRouter);
router.use(adminKeysRouter);
router.use(adminClaimsRouter);
router.use(adminDiscountsRouter);
router.use(adminCustomersRouter);
router.use(adminReviewsRouter);
router.use(adminBannersRouter);
router.use(adminPagesRouter);
router.use(adminSettingsRouter);
router.use(adminSettingsExtraRouter);
router.use(adminWebhooksChatRouter);
router.use(adminAuditRouter);
router.use(adminBalanceRouter);
router.use(adminUpsellRouter);
router.use(adminHomepageRouter);
router.use(adminBrandsRouter);
router.use(adminEmailTemplatesRouter);
router.use(adminTaxRouter);
router.use(adminUsersRouter);
router.use(adminRefundsRouter);
router.use(adminNotificationsRouter);
router.use(adminSeoTrackingRouter);
router.use(adminGiftCardsRouter);
router.use(giftCardsRouter);
router.use(couponsRouter);
router.use(ordersRouter);
router.use(checkoutOffersRouter);
router.use(orderLookupRouter);
router.use(wishlistRouter);
router.use(currenciesRouter);
router.use(webhooksRouter);
router.use(searchRouter);

export default router;
