import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import authGoogleRouter from "./auth-google";
import adminRouter from "./admin";
import adminDashboardRouter from "./admin-dashboard";
import adminAnalyticsRouter from "./admin-analytics";
import adminProductsRouter from "./admin-products";
import adminCategoriesRouter from "./admin-categories";
import adminOrdersRouter from "./admin-orders";
import adminKeysRouter from "./admin-keys";
import adminClaimsRouter from "./admin-claims";
import adminDiscountsRouter from "./admin-discounts";
import adminCustomersRouter from "./admin-customers";
import adminReviewsRouter from "./admin-reviews";
import adminBannersRouter from "./admin-banners";
import adminPagesRouter from "./admin-pages";
import adminSettingsRouter from "./admin-settings";
import adminSettingsExtraRouter from "./admin-settings-extra";
import adminWebhooksChatRouter from "./admin-webhooks-chat";
import adminAuditRouter from "./admin-audit";
import adminBalanceRouter from "./admin-balance";
import adminUpsellRouter from "./admin-upsell";
import adminHomepageRouter from "./admin-homepage";
import adminBrandsRouter from "./admin-brands";
import adminEmailTemplatesRouter from "./admin-email-templates";
import adminTaxRouter from "./admin-tax";
import adminUsersRouter from "./admin-users";
import adminRefundsRouter from "./admin-refunds";
import adminNotificationsRouter from "./admin-notifications";
import adminSeoTrackingRouter from "./admin-seo-tracking";
import adminGiftCardsRouter from "./admin-gift-cards";
import adminAffiliatesRouter from "./admin-affiliates";
import adminAbandonedCartsRouter from "./admin-abandoned-carts";
import adminAlertsRouter from "./admin-alerts";
import adminQaRouter from "./admin-qa";
import adminNewsletterRouter from "./admin-newsletter";
import adminFlashSalesRouter from "./admin-flash-sales";
import adminLoyaltyRouter from "./admin-loyalty";
import adminBundlesRouter from "./admin-bundles";
import adminSupportRouter from "./admin-support";
import supportTicketsRouter from "./support-tickets";
import walletRouter from "./wallet";
import adminWalletRouter from "./admin-wallet";
import loyaltyRouter from "./loyalty";
import bundlesRouter from "./bundles";
import flashSalesRouter from "./flash-sales";
import alertsRouter from "./alerts";
import qaRouter from "./qa";
import newsletterRouter from "./newsletter";
import affiliatesRouter from "./affiliates";
import giftCardsRouter from "./gift-cards";
import abandonedCartsRouter from "./abandoned-carts";
import couponsRouter from "./coupons";
import ordersRouter from "./orders";
import checkoutOffersRouter from "./checkout-offers";
import orderLookupRouter from "./order-lookup";
import wishlistRouter from "./wishlist";
import currenciesRouter from "./currencies";
import webhooksRouter from "./webhooks";
import checkoutServicesRouter from "./checkout-services";
import adminCheckoutServicesRouter from "./admin-checkout-services";
import searchRouter from "./search";
import trustpilotRouter from "./trustpilot";
import socialProofRouter from "./social-proof";
import adminSocialProofRouter from "./admin-social-proof";
import i18nRouter from "./i18n";
import adminI18nRouter from "./admin-i18n";
import blogRouter from "./blog";
import adminBlogRouter from "./admin-blog";
import consentRouter from "./consent";
import quotesRouter from "./quotes";
import adminQuotesRouter from "./admin-quotes";
import surveysRouter from "./surveys";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(authGoogleRouter);
router.use(adminRouter);
router.use(adminDashboardRouter);
router.use(adminAnalyticsRouter);
router.use(adminProductsRouter);
router.use(adminCategoriesRouter);
router.use(adminOrdersRouter);
router.use(adminKeysRouter);
router.use(adminClaimsRouter);
router.use(adminDiscountsRouter);
router.use(adminCustomersRouter);
router.use(adminReviewsRouter);
router.use(adminBannersRouter);
router.use(adminPagesRouter);
router.use(adminSettingsRouter);
router.use(adminSettingsExtraRouter);
router.use(adminWebhooksChatRouter);
router.use(adminAuditRouter);
router.use(adminBalanceRouter);
router.use(adminUpsellRouter);
router.use(adminHomepageRouter);
router.use(adminBrandsRouter);
router.use(adminEmailTemplatesRouter);
router.use(adminTaxRouter);
router.use(adminUsersRouter);
router.use(adminRefundsRouter);
router.use(adminNotificationsRouter);
router.use(adminSeoTrackingRouter);
router.use(adminGiftCardsRouter);
router.use(adminAffiliatesRouter);
router.use(adminAbandonedCartsRouter);
router.use(adminAlertsRouter);
router.use(adminQaRouter);
router.use(adminNewsletterRouter);
router.use(adminFlashSalesRouter);
router.use(adminLoyaltyRouter);
router.use(adminBundlesRouter);
router.use(adminSupportRouter);
router.use(supportTicketsRouter);
router.use(walletRouter);
router.use(adminWalletRouter);
router.use(loyaltyRouter);
router.use(bundlesRouter);
router.use(flashSalesRouter);
router.use(alertsRouter);
router.use(qaRouter);
router.use(newsletterRouter);
router.use(affiliatesRouter);
router.use(abandonedCartsRouter);
router.use(giftCardsRouter);
router.use(couponsRouter);
router.use(ordersRouter);
router.use(checkoutOffersRouter);
router.use(orderLookupRouter);
router.use(wishlistRouter);
router.use(currenciesRouter);
router.use(webhooksRouter);
router.use(checkoutServicesRouter);
router.use(adminCheckoutServicesRouter);
router.use(searchRouter);
router.use(trustpilotRouter);
router.use(socialProofRouter);
router.use(adminSocialProofRouter);
router.use(i18nRouter);
router.use(adminI18nRouter);
router.use(blogRouter);
router.use(adminBlogRouter);
router.use(consentRouter);
router.use(quotesRouter);
router.use(adminQuotesRouter);
router.use(surveysRouter);

export default router;
